
services:
  db:
    image: mysql:8.0
    container_name: app-mysql
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  php:
    build:
      context: ./docker/php
    container_name: app-php
    working_dir: /var/www/app
    volumes:
      - ./app:/var/www/app:cached
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
    environment:
      # Xdebug activado por defecto
      XDEBUG_MODE: debug,develop
      PHP_IDE_CONFIG: serverName=app.local
    expose:
      - "9003" # puerto Xdebug dentro de la red docker
    depends_on:
      db:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway" # Descubrimiento host (Linux/macOS/Windows modern)


  nginx:
    image: nginx:1.27-alpine
    container_name: app-nginx
    ports:
      - "8080:80" # http://localhost:8080
    volumes:
      - ./app:/var/www/app:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php


volumes:
  db-data: